### PR TITLE
Create checking_software_development_on_Github.md

### PR DESCRIPTION
**Pull request by acc483**

### CODE REVIEW

**Comment by acc483** [comment]
@KaPatel15 and @cuhkcd please comment on this

**Comment by cuhkcd** [comment]
@acc483 Can you please add some more details on uploading images?

**Comment by acc483** [comment]
I added a line on how to upload image @karishma please comment

**Comment by cuhkcd** [comment]
:+1:

**Comment by KaPatel15** [comment]
:+1:

**Pull request merged**
