### PR TITLE
Communication with developer

### PR DESCRIPTION
**Pull request by cuhkcd**
This is a summary of how to communicate with developer

### CODE REVIEW

**Comment by cuhkcd** [comment]
@acc483 @KaPatel15 please comment

**Comment by acc483** [comment]
Please get rid of the link to the vote for hillary and paste something more related to the class

**Comment by cuhkcd** [comment]
I have updated the file and gotten rid of the link @acc483 please check @KaPatel15 please let me know if you have anything more to add

**Comment by acc483** [comment]
:+1:

**Comment by KaPatel15** [comment]
:+1:

**Pull request merged**
