### PR TITLE
Questions to ask when hiring

### PR DESCRIPTION
**Pull request by KaPatel15**
This is a summary of what questions to ask when hiring developers

### CODE REVIEW

**Comment by KaPatel15** [comment]
@acc483 @cuhkcd please comment

**Comment by acc483** [comment]
@KaPatel15 Can you add some questions that check whether the developer is eager to learn new stuff

**Comment by KaPatel15** [comment]
@acc483 please check if you are happy now @cuhkcd please see if you have any additional comment

**Comment by acc483** [comment]
:+1:

**Comment by cuhkcd** [comment]
:+1:

**Pull request merged**
